### ISSUE TITLE
perm

### ISSUE THREAD

**Issue by honixxxqw** [By1337/BAuction#2]
Pls give permisioin to luckperms

**Comment by By1337** [comment]
> /bauc reload - **bauc.reload**
> /bauc sell - **bauc.sell**
> /bauc search - **bauc.search**
> /bauc - **bauc.use**
> /bauc admin - **bauc.admin**
> - /bauc admin addTag \- **bauc.admin.addTag**
> - /bauc admin open \- **bauc.admin.open**
> - /bauc admin push - **bauc.admin.push**
> - /bauc admin parse - **bauc.parse**
> - /bauc admin parse tags - **bauc.parse.tags**
> - /bauc admin parse nbt - **bauc.parse.nbt**
